---
name: 🐛 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "needs triage"]
assignees:
  - salehye
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of our package are you running?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you using?
      placeholder: "8.4.0"
    validations:
      required: true

  - type: input
    id: laravel-version
    attributes:
      label: Laravel Version
      description: What version of Laravel are you using?
      placeholder: "12.0.0"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create setting with key '...'
        2. Call Settings::get('...')
        3. See error
    validations:
      required: true

  - type: input
    id: sample-code
    attributes:
      label: Sample Code
      description: Paste a minimal, complete, and verifiable piece of code
      render: php

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
